export const surveyList = [
  {
    name: 'Automobiles',
    image: 'img/Automobiles.png',
    completesLeft: 'NEW',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Lifestyle',
    image: 'img/Lifestyle.png',
    completesLeft: '8 completes left',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Food',
    image: 'img/Food.png',
    completesLeft: '8 completes left',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Automobiles',
    image: 'img/Automobiles.png',
    completesLeft: '8 completes left',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Technology',
    image: 'img/Technology.png',
    completesLeft: 'NEW',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Food',
    image: 'img/Food.png',
    completesLeft: 'NEW',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Lifestyle',
    image: 'img/Lifestyle.png',
    completesLeft: 'NEW',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
  {
    name: 'Technology',
    image: 'img/Technology.png',
    completesLeft: '8 completes left',
    completionTime: 2,
    qualificationsForSurvey: 3,
    virtualCurrency: 30000,
  },
];
